build:
  maxIssues: 10
  excludeCorrectable: false

config:
  validation: true

console-reports:
  active: true
  exclude: []

output-reports:
  active: true
  exclude: []

comments:
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
    endOfSentenceFormat: '([.?!]){1,3}'
  OutdatedDocumentation:
    active: false

style:
  ReturnCount:
    active: true
    max: 3
    excludedFunctions:
      - 'toString'
      - 'hashCode'
      - 'equals'
  ThrowsCount:
    active: true
  UseDataClass:
    active: true
  AlsoCouldBeApply:
    active: false

formatting:
  ChainWrapping:
    active: true
  NoLineBreakAfterElse:
    active: true
  NoMultipleSpaces:
    active: true
  NoSemicolons:
    active: true
  NoTrailingSpaces:
    active: true
